"""
Inventory and optimise gallery images, then (re)write assets/gallery/gallery-data.js.

    python tools/build_gallery.py              # inventory + optimise + update data
    python tools/build_gallery.py --inventory  # only report what is in the folders

Source folders (originals are never modified or deleted):
    assets/Training_imgs  -> category "training"
    assets/banners        -> category "banners"
    assets/certificates   -> category "certificates"   (optional)

For every image this creates, under assets/gallery/<category>/:
    <name>-480.webp / -960.webp / -1600.webp   (only widths up to the original)
    <name>-480.avif / -960.avif / -1600.avif
    <name>-960.jpg                              (fallback for old browsers)
EXIF data (including GPS location) is stripped from the copies.

Captions you add in gallery-data.js (title, description, date, alt, tags,
featured, homepage) are preserved when the script is run again.
A human-readable report is written to assets/gallery/INVENTORY.md.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

from PIL import Image, ImageOps, features

ROOT = Path(__file__).resolve().parent.parent
ASSETS = ROOT / "assets"
OUT = ASSETS / "gallery"
DATA_FILE = OUT / "gallery-data.js"
REPORT = OUT / "INVENTORY.md"

SOURCES = {
    "training": ASSETS / "Training_imgs",
    "banners": ASSETS / "Banner" if (ASSETS / "Banner").exists() else ASSETS / "banners",
    "certificates": ASSETS / "certificates",
}
IMAGE_EXT = {".jpg", ".jpeg", ".png", ".webp", ".avif", ".bmp", ".tif", ".tiff"}
WIDTHS = [480, 960, 1600]
FALLBACK_WIDTH = 960
EDITABLE = ["title", "description", "date", "alt", "tags", "featured", "homepage"]
LOW_RES = 900  # long side below this is flagged

HEADER = """/**
 * GALLERY DATA — generated by tools/build_gallery.py, safe to edit by hand.
 *
 * Only fill in title / description / date / alt once they are verified.
 * These fields are kept when the script runs again:
 *   title        short caption shown on hover and in the lightbox
 *   description  one or two sentences for the lightbox
 *   date         e.g. "March 2025"
 *   alt          what the photo shows, for screen readers
 *   tags         extra filters, e.g. ["Workshop"]
 *   featured     true = shown large on the gallery page
 *   homepage     true = picked for the homepage preview (first 5 used)
 *
 * Keep valid JSON inside the brackets (double quotes, no trailing commas).
 */
window.GALLERY_ITEMS = """


def slugify(stem: str) -> str:
    s = re.sub(r"[^a-z0-9]+", "-", stem.lower()).strip("-")
    return s or "image"


def dhash(img: Image.Image, size: int = 8) -> int:
    g = img.convert("L").resize((size + 1, size), Image.Resampling.LANCZOS)
    px = list(g.get_flattened_data() if hasattr(g, "get_flattened_data") else g.getdata())
    bits = 0
    for row in range(size):
        for col in range(size):
            left = px[row * (size + 1) + col]
            right = px[row * (size + 1) + col + 1]
            bits = (bits << 1) | (left > right)
    return bits


def load_existing() -> dict:
    if not DATA_FILE.exists():
        return {}
    text = DATA_FILE.read_text(encoding="utf-8")
    start = text.find("[", text.find("window.GALLERY_ITEMS"))
    end = text.rfind("]")
    if start < 0 or end < 0:
        return {}
    try:
        items = json.loads(text[start:end + 1])
    except json.JSONDecodeError as e:
        sys.exit(f"gallery-data.js is not valid JSON ({e}). Fix it before re-running.")
    return {it.get("source"): it for it in items if it.get("source")}


def scan():
    found = []
    for category, folder in SOURCES.items():
        if not folder.exists():
            continue
        for path in sorted(folder.rglob("*")):
            if path.is_file():
                found.append((category, path))
    return found


def inspect(category, path):
    info = {
        "category": category,
        "path": path,
        "source": path.relative_to(ASSETS).as_posix(),
        "ext": path.suffix.lower(),
        "bytes": path.stat().st_size,
    }
    if info["ext"] not in IMAGE_EXT:
        info["error"] = "not a supported image type"
        return info
    try:
        with Image.open(path) as im:
            im = ImageOps.exif_transpose(im)
            info["width"], info["height"] = im.size
            info["mode"] = im.mode
            info["dhash"] = dhash(im)
    except Exception as e:  # corrupt / unsupported (e.g. HEIC without plugin)
        info["error"] = f"could not open ({e.__class__.__name__})"
        return info
    info["sha1"] = hashlib.sha1(path.read_bytes()).hexdigest()
    w, h = info["width"], info["height"]
    r = w / h
    info["orientation"] = "square" if 0.9 <= r <= 1.1 else ("landscape" if r > 1 else "portrait")
    info["low_res"] = max(w, h) < LOW_RES
    return info


def optimise(info, name, formats):
    dest = OUT / info["category"]
    dest.mkdir(parents=True, exist_ok=True)
    src_mtime = info["path"].stat().st_mtime
    # standard widths below the original, plus the original itself (capped at the largest)
    widths = sorted({w for w in WIDTHS if w < info["width"]} | {min(info["width"], WIDTHS[-1])})
    fb_width = max([w for w in widths if w <= FALLBACK_WIDTH] or [widths[0]])

    targets = [(w, f) for w in widths for f in formats] + [(fb_width, "jpg")]
    todo = [(w, f) for (w, f) in targets
            if not (dest / f"{name}-{w}.{f}").exists() or (dest / f"{name}-{w}.{f}").stat().st_mtime < src_mtime]
    if todo:
        with Image.open(info["path"]) as im:
            im = ImageOps.exif_transpose(im)
            if im.mode in ("RGBA", "LA", "P"):
                im = im.convert("RGBA")
                bg = Image.new("RGB", im.size, (255, 255, 255))
                bg.paste(im, mask=im.split()[-1])
                im = bg
            else:
                im = im.convert("RGB")
            for w, f in todo:
                h = round(im.height * w / im.width)
                out = im if w == im.width else im.resize((w, h), Image.Resampling.LANCZOS)
                path = dest / f"{name}-{w}.{f}"
                if f == "webp":
                    out.save(path, "WEBP", quality=80, method=6)
                elif f == "avif":
                    out.save(path, "AVIF", quality=55, speed=6)
                else:
                    out.save(path, "JPEG", quality=82, optimize=True, progressive=True)
    return widths, fb_width, len(todo)


def human(n):
    return f"{n / 1_048_576:.1f} MB" if n >= 1_048_576 else f"{n / 1024:.0f} KB"


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    ap = argparse.ArgumentParser()
    ap.add_argument("--inventory", action="store_true", help="report only, do not write files")
    args = ap.parse_args()

    formats = ["avif", "webp"] if features.check("avif") else ["webp"]
    files = scan()
    infos = [inspect(c, p) for c, p in files]
    ok = [i for i in infos if "error" not in i]
    bad = [i for i in infos if "error" in i]

    # exact duplicates (same bytes) and near duplicates (visually similar)
    seen_sha = {}
    exact_dupes = []
    for i in ok:
        if i["sha1"] in seen_sha:
            exact_dupes.append((i, seen_sha[i["sha1"]]))
            i["duplicate_of"] = seen_sha[i["sha1"]]["source"]
        else:
            seen_sha[i["sha1"]] = i
    unique = [i for i in ok if "duplicate_of" not in i]
    near = []
    for a in range(len(unique)):
        for b in range(a + 1, len(unique)):
            if bin(unique[a]["dhash"] ^ unique[b]["dhash"]).count("1") <= 4:
                near.append((unique[a], unique[b]))

    # ---- report ----
    lines = ["# Gallery inventory", ""]
    for cat, folder in SOURCES.items():
        cat_items = [i for i in infos if i["category"] == cat]
        exists = folder.exists()
        lines.append(f"## {cat} — `{folder.relative_to(ROOT).as_posix()}`" + ("" if exists else " (folder not found)"))
        if not cat_items:
            lines += ["", "_No files._", ""]
            continue
        lines += ["", "| File | Format | Size | Dimensions | Orientation | Notes |", "|---|---|---|---|---|---|"]
        for i in cat_items:
            notes = []
            if "error" in i:
                notes.append(i["error"])
            if i.get("low_res"):
                notes.append("low resolution")
            if i.get("duplicate_of"):
                notes.append(f"exact duplicate of {i['duplicate_of']}")
            dims = f"{i['width']}×{i['height']}" if "width" in i else "—"
            lines.append(f"| {i['path'].name} | {i['ext'].lstrip('.')} | {human(i['bytes'])} | {dims} | {i.get('orientation', '—')} | {'; '.join(notes)} |")
        lines.append("")
    if near:
        lines += ["## Possible near-duplicates (review manually)", ""]
        lines += [f"- {a['source']}  ≈  {b['source']}" for a, b in near]
        lines.append("")
    by_orient = {o: sum(1 for i in ok if i["orientation"] == o) for o in ("landscape", "portrait", "square")}
    summary = (f"{len(infos)} files · {len(ok)} readable images · {len(exact_dupes)} exact duplicates · "
               f"{len(near)} near-duplicate pairs · {len(bad)} unreadable · "
               f"landscape {by_orient['landscape']}, portrait {by_orient['portrait']}, square {by_orient['square']}")
    lines.insert(2, summary + "\n")
    print(summary)

    if args.inventory:
        print("\n".join(lines))
        return

    OUT.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # ---- optimise + data ----
    existing = load_existing()
    items, used_names, written = [], set(), 0
    for i in unique:
        base_name = slugify(i["path"].stem)
        name = base_name
        n = 2
        while (i["category"], name) in used_names:
            name = f"{base_name}-{n}"
            n += 1
        used_names.add((i["category"], name))

        widths, fb, count = optimise(i, name, formats)
        written += count
        rel = f"assets/gallery/{i['category']}/{name}"
        item = {
            "id": f"{i['category']}/{name}",
            "category": i["category"],
            "source": i["source"],
            "base": rel,
            "widths": widths,
            "formats": formats,
            "fallback": f"{rel}-{fb}.jpg",
            "width": i["width"],
            "height": i["height"],
            "title": "", "description": "", "date": "", "alt": "",
            "tags": [], "featured": False, "homepage": False,
        }
        prev = existing.get(i["source"])
        if prev:
            for k in EDITABLE:
                if k in prev:
                    item[k] = prev[k]
        items.append(item)

    removed = sorted(set(existing) - {i["source"] for i in items})
    DATA_FILE.write_text(HEADER + json.dumps(items, indent=2, ensure_ascii=False) + ";\n", encoding="utf-8")

    print(f"{len(items)} gallery items written to {DATA_FILE.relative_to(ROOT).as_posix()}")
    print(f"{written} optimised files created or refreshed (formats: {', '.join(formats)} + jpg fallback)")
    if exact_dupes:
        print(f"{len(exact_dupes)} exact duplicates skipped — see INVENTORY.md")
    if removed:
        print("Entries removed because their source file is gone: " + ", ".join(removed))
    if bad:
        print(f"{len(bad)} files could not be read — see INVENTORY.md")


if __name__ == "__main__":
    main()
